# Generated file used for preloading a child image
set(CMAKE_BUILD_TYPE "" CACHE INTERNAL "NCS child image controlled")
set(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE INTERNAL "NCS child image controlled")
set(BOARD_DIR "D:/SDK/ncs_v1.9.1/v1.9.1/zephyr/boards/arm/nrf9160dk_nrf9160" CACHE INTERNAL "NCS child image controlled")
set(BOARD_REVISION "0.7.0" CACHE INTERNAL "NCS child image controlled")
set(ZEPHYR_TOOLCHAIN_VARIANT "gnuarmemb" CACHE INTERNAL "NCS child image controlled")
set(GNUARMEMB_TOOLCHAIN_PATH "D:/zepyth/v1.9.1/toolchain/opt" CACHE INTERNAL "NCS child image controlled")
set(BOARD nrf9160dk_nrf9160 CACHE INTERNAL "NCS child image controlled")
set(CONFIG_SPM_SECURE_SERVICES y CACHE INTERNAL "NCS child image controlled")
set(CONFIG_SPM_SERVICE_FIND_FIRMWARE_INFO y CACHE INTERNAL "NCS child image controlled")
set(CONFIG_SPM_SERVICE_READ y CACHE INTERNAL "NCS child image controlled")
set(CONFIG_SPM_SERVICE_RNG y CACHE INTERNAL "NCS child image controlled")
set(OVERLAY_CONFIG ;D:/SDK/ncs_v1.9.1/v1.9.1/nrf/subsys/partition_manager/partition_manager_enabled.conf CACHE INTERNAL "NCS child image controlled")
set(OVERLAY_CONFIG ;D:/SDK/ncs_v1.9.1/v1.9.1/nrf/subsys/partition_manager/partition_manager_enabled.conf CACHE INTERNAL "NCS child image controlled")
