add_custom_target(spm_shared_property_target)
set_property(TARGET spm_shared_property_target  PROPERTY KERNEL_HEX_NAME;zephyr.hex)
set_property(TARGET spm_shared_property_target  PROPERTY ZEPHYR_BINARY_DIR;D:/SDK/ncs_v1.9.1/v1.9.1/zephyr/samples/basic/button/build_nrf9160dk_nrf9160/spm/zephyr)
set_property(TARGET spm_shared_property_target  PROPERTY KERNEL_ELF_NAME;zephyr.elf)
set_property(TARGET spm_shared_property_target  PROPERTY BUILD_BYPRODUCTS;D:/SDK/ncs_v1.9.1/v1.9.1/zephyr/samples/basic/button/build_nrf9160dk_nrf9160/spm/zephyr/zephyr.hex;D:/SDK/ncs_v1.9.1/v1.9.1/zephyr/samples/basic/button/build_nrf9160dk_nrf9160/spm/zephyr/zephyr.elf)
set_property(TARGET spm_shared_property_target APPEND PROPERTY BUILD_BYPRODUCTS;D:/SDK/ncs_v1.9.1/v1.9.1/zephyr/samples/basic/button/build_nrf9160dk_nrf9160/spm/libspmsecureentries.a)
set_property(TARGET spm_shared_property_target APPEND PROPERTY PM_YML_DEP_FILES;D:/SDK/ncs_v1.9.1/v1.9.1/nrf/samples/spm/pm.yml)
set_property(TARGET spm_shared_property_target APPEND PROPERTY PM_YML_FILES;D:/SDK/ncs_v1.9.1/v1.9.1/zephyr/samples/basic/button/build_nrf9160dk_nrf9160/spm/zephyr/include/generated/pm.yml)
set_property(TARGET spm_shared_property_target APPEND PROPERTY PM_YML_DEP_FILES;D:/SDK/ncs_v1.9.1/v1.9.1/nrf/subsys/partition_manager/pm.yml.trustzone)
set_property(TARGET spm_shared_property_target APPEND PROPERTY PM_YML_FILES;D:/SDK/ncs_v1.9.1/v1.9.1/zephyr/samples/basic/button/build_nrf9160dk_nrf9160/spm/modules/nrf/subsys/partition_manager/pm.yml.trustzone)
